
// DASHBOARD
export const STORAGE_TRANSACTIONS = 'STORAGE_TRANSACTIONS';
export const STORAGE_VOUCHERS = 'STORAGE_VOUCHERS';
export const STORAGE_TOKEN = 'STORAGE_TOKEN';
export const STORAGE_CID = 'STORAGE_CID';
export const STORAGE_PHONE = 'STORAGE_PHONE';
export const STORAGE_USER = 'STORAGE_USER';
export const STORAGE_INTERESTS = 'STORAGE_INTERESTS';
export const STORAGE_POINTS = 'STORAGE_POINTS';
export const STORAGE_BUSINESS_INDEX = 'STORAGE_BUSINESS_INDEX';
export const STORAGE_WALLET_SETUP = 'STORAGE_WALLET_SETUP';

export * from "./dash/actions";